spring:
  application:
    name: demo
  profiles:
    default: local
  redis:
    host: 192.168.0.49
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
