INSERT INTO product (name) VALUES ('아이스크림');
INSERT INTO product (name) VALUES ('카페라떼');
INSERT INTO product (name) VALUES ('바닐라라떼');
INSERT INTO product (name) VALUES ('콜드블루');
INSERT INTO product (name) VALUES ('모카');
INSERT INTO product (name) VALUES ('에스프레소');
INSERT INTO product (name) VALUES ('그린티');
INSERT INTO product (name) VALUES ('블랙티');
INSERT INTO product (name) VALUES ('레몬에이드');
INSERT INTO product (name) VALUES ('꿀커피');

INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (1, 3, 3);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (2, 7, 7);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (3, 1, 1);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (4, 9, 9);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (5, 5, 5);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (6, 2, 2);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (7, 8, 8);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (8, 4, 4);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (9, 6, 6);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (10, 0, 0);
